routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// route vers les biens de l'auth
route::get('/rooms/advertiser', 'RoomController@showAdvertiserRoom')
         ->name('rooms.advertiser');

// ensemble des routes concernant une room
Route::resource('rooms','RoomController')->parameters(['room' => '[0-9]+']);

// route vers mes reservations
route::get('/leasings/userLeasings', 'LeasingController@showAuthLeasings')
         ->name('leasings.userLeasings');

// route vers les biens appartenant a l'auth et qui sont loués
route::get('/leasings/authLeasingsByUser', 'LeasingController@showAuthLeasingsReserved')
         ->name('leasings.authLeasingsByUser');

// ensemble des routes concernant un leasing
Route::resource('rooms/{room}/leasings','leasingController')
                ->parameters([
                            'room' => '[0-9]+',
                            'leasing' => '[0-9]+'
                            ]);

// route qui renvoie vers la page home
Route::get('/', 'HomeController@index')->name('home');

resources/views/errors.blade.php
{{-- affichage des erreurs si il y en a --}}
@if ($errors->any())
    <div class="errors">
        <ul>
            {{-- boucle sur les type d'erreur --}}
            @foreach ($errors->all() as $error)

            <li>{{ $error }}</li>        

            @endforeach
        </ul>            

    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'acceuil')  

@section('content')

Bienvenu sur AIR BNB
    
@endsection

resources/views/nav.blade.php
<ul class="nav justify-content-center">

        <li class="nav-item">
            <a class="nav-link" href="{{ route('home') }}">{{ __('Acceuil') }}</a> 
        </li>

                    
        <li class="nav-item">
            <a class="nav-link" href="{{ route('rooms.index') }}">{{ __('Chambres') }}</a>           
        </li> 
                     
        
        @auth

        @if (Auth::user()->role_id == 1)
                <li class="nav-item">
                                <a class="nav-link" href="{{ route('rooms.create') }}">{{ __('Creer une location') }}</a>           
                </li>               
                <li class="nav-item">
                        <a class="nav-link" href="{{ route('rooms.advertiser') }}">{{ __('Mes biens') }}</a>           
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ route('leasings.authLeasingsByUser') }}">{{ __('Mes biens loués') }}</a>           
                </li>
        @endif 

        <li class="nav-item">
                <a class="nav-link" href="{{ route('leasings.userLeasings') }}">{{ __('Mes reservations') }}</a>           
        </li>              
                
        @endauth
                   
        
    </ul>

    