routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// route vers les biens de l'auth
route::get('/rooms/advertiser', 'RoomController@showAdvertiserRoom')
         ->name('rooms.advertiser');

// ensemble des routes concernant une room
Route::resource('rooms','RoomController')->parameters(['room' => '[0-9]+']);

// route vers mes reservations
route::get('/leasings/userLeasings', 'LeasingController@showAuthLeasings')
         ->name('leasings.userLeasings');

// route vers les biens appartenant a l'auth et qui sont loués
route::get('/leasings/authLeasingsByUser', 'LeasingController@showAuthLeasingsReserved')
         ->name('leasings.authLeasingsByUser');

// ensemble des routes concernant un leasing
Route::resource('rooms/{room}/leasings','leasingController')
                ->parameters([
                            'room' => '[0-9]+',
                            'leasing' => '[0-9]+'
                            ]);

// route qui renvoie vers la page home
Route::get('/', 'HomeController@index')->name('home');

app/Leasing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Leasing extends Model
{
    //sert pour les injection dans la bdd
    protected $fillable = ['datestart',
                            'dateend',
                            'user_id',
                            'room_id'];

    //relation une option peut appartenir à plusieur room
    function room(){
        return $this->belongsTo(Room::class);
    }

        
}

app/Http/Controllers/LeasingController.php
<?php

namespace App\Http\Controllers;

use App\leasing;
use App\Room;
use Auth;
use App\User;
use Illuminate\Http\Request;

class LeasingController extends Controller
{
    function __construct(){
        //les trois middleware ont été creer par moi même
        //si l'utilisateur est authentifié, il peut acceder à index, create et store 
        $this->middleware('auth', ['only' => ['create','store','show']]);       
        
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Room $room)
    {
        return view ('leasings.create',compact('room'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Room $room)
    {
        //validation des champs
        $fields = $request->validate([
                                    'datestart'=>'required',
                                    'dateend'=>'required',
                                    ]);
        
        //ajout de l'user
        $fields['user_id'] = Auth::user()->id;

        //ajout de la room
        $fields['room_id'] = $room->id;
        
        //creation de la reservation
        $leasing = Leasing::create($fields);

        //redirection vers la vue
        return redirect(route('rooms.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\leasing  $leasing
     * @return \Illuminate\Http\Response
     */
    public function show(leasing $leasing)
    {
        //
    }

    // récupère mes reservations
    public function showAuthLeasings()
    {
                
        $leasings = Auth::user()->leasings;
                                
        return view('leasings.userLeasings',compact('leasings'));
                
    }

    // affiche mes biens loués
    public function showAuthLeasingsReserved()
        {

        $rooms = Auth::user()->rooms;
                              
               
        // dd($reservations);

        return view('leasings.authLeasingsByUser',compact('rooms'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\leasing  $leasing
     * @return \Illuminate\Http\Response
     */
    public function edit(leasing $leasing)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\leasing  $leasing
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, leasing $leasing)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\leasing  $leasing
     * @return \Illuminate\Http\Response
     */
    public function destroy(leasing $leasing)
    {
        //
    }
}

resources/views/leasings/authLeasingsByUser.blade.php
etend app.blade.php
@extends('layouts.app')

{{-- ajoute le titre "vos locations " dans l'onglet --}}
@section('title', 'Vos locations')

@section('content')

<div class="d-flex justify-content-around row">
        
    @foreach ($rooms as $room)
        @foreach ($room->leasings as $leasing)            
            <div class="card" style="width: 20rem;">
                <img src="{{$room->picture1}}" class="card-img-top">
            
                    <div class="card-body">
                        <h5 class="card-title">Pays : {{$room->address->country}}</h5>                
                        <h5 class="card-title">Ville : {{$room->address->city}}</h5>            
                    </div>            
                <p class="card-text"><small class="text-muted">
                    Vous avez loué du {{$leasing->datestart}} au {{$leasing->dateend}}</small></p>
                    <a href="{{route('rooms.show', $room)}}" class="btn btn-primary">Détails</a>
        </div> 
        @endforeach      
    @endforeach      
        
    
        
</div>

@endsection 

resources/views/leasings/create.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "Ajouter un bien " dans l'onglet --}}
@section('title', 'Louer un bien')
 
{{-- creation d'un header --}}
@section('header')

    
@endsection

{{-- creation du contenu --}}
@section('content')

{{-- affichage des erreurs --}}
@include('errors')

{{-- formulaire de location --}}
<div class="card" style="width: 50rem;">
    <form action="{{route('leasings.store',$room)}}" method="POST">

        {{-- champs de protection CSRF --}}
        @csrf

        <h3>Formulaire de reservation :</h3>        
                
        {{-- Date d'arrivé à la location --}}
        <div class="form-group">
            <label> Date d'arrivée</label>
        <input type="date" name="datestart" class="form-control">
        </div>
        
        {{-- Date de départ de la location --}}
        <div class="form-group">
            <label> Date de départ</label>
            <input type="date" name="dateend" class="form-control">
        </div>                   

        <button type="submit" class="btn btn-primary">louer</button>
    </form>
    
</div>
    
@endsection

resources/views/leasings/userLeasings.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "vos locations " dans l'onglet --}}
@section('title', 'Vos locations')

@section('content')

<div class="d-flex justify-content-around row">
        
    @foreach ($leasings as $leasing)            
        <div class="card" style="width: 20rem;">
            <img src="{{asset("storage/images/{$leasing->room->picture1}")}}" class="card-img-top">
           
                <div class="card-body">
                    <h5 class="card-title">Pays : {{$leasing->room->address->country}}</h5>                
                    <h5 class="card-title">Ville : {{$leasing->room->address->city}}</h5>            
                </div>            
            <p class="card-text"><small class="text-muted">
                Vous avez loué du {{$leasing->datestart}} au {{$leasing->dateend}}</small></p>
                <a href="{{route('rooms.show', $leasing->room)}}" class="btn btn-primary">Détails</a>
        </div> 
    @endforeach      
        
    
        
</div>

@endsection