routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// route vers les biens de l'auth
route::get('/rooms/advertiser', 'RoomController@showAdvertiserRoom')
         ->name('rooms.advertiser');

// ensemble des routes concernant une room
Route::resource('rooms','RoomController')->parameters(['room' => '[0-9]+']);

// route vers mes reservations
route::get('/leasings/userLeasings', 'LeasingController@showAuthLeasings')
         ->name('leasings.userLeasings');

// route vers les biens appartenant a l'auth et qui sont loués
route::get('/leasings/authLeasingsByUser', 'LeasingController@showAuthLeasingsReserved')
         ->name('leasings.authLeasingsByUser');

// ensemble des routes concernant un leasing
Route::resource('rooms/{room}/leasings','leasingController')
                ->parameters([
                            'room' => '[0-9]+',
                            'leasing' => '[0-9]+'
                            ]);

// route qui renvoie vers la page home
Route::get('/', 'HomeController@index')->name('home');

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    //sert pour les injection dans la bdd
    protected $fillable = [ 'description',
                            'type_id',
                            'area',
                            'sleeping',
                            'price',
                            'datestart',
                            'dateend',
                            'picture1',
                            'picture2',
                            'picture3',
                            'address_id',
                            'user_id'];

    //relation une reservations peut appartenir qu'a une room
    // function leasings(){
    //     return $this->belongsTo(Leasing::class);
    // }
    function leasings(){
        return $this->hasMany(Leasing::class);
    }
    //relation une option peut appartenir à plusieur room
    function options(){
        return $this->belongsToMany(Option::class);
    }

    //relation une adress ne peut apparteir qu'à une seule room
    function address(){
        return $this->belongsTo(Address::class);
    }

    //relation un user ne peut avoir qu'une room
    function user(){
        return $this->belongsTo(User::class);
    }

    //relation un type ne peut avoir qu'une room
    function type(){
        return $this->belongsTo(Type::class);
    }

    // selectionne et enregistre les options pour une nouvelle location
    function addOptions(array $options){
        $this->options()->attach( $options);
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Room;
use App\Type;
use App\Option;
use App\Address;
use App\User;
use Auth;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    function __construct(){
        //les trois middleware ont été creer par moi même
        //si l'utilisateur n'est pas authentifié, il ne peut acceder qu'à index et show
        $this->middleware('auth', ['except' => ['index', 'show']]);
        //si l'utilisateur est authentifié en tand que advertiser, il peut creer
        $this->middleware('check.advertiser.room', ['only'=> ['create','store']]);
        //si l'utilisateur est authentifié en tand que l'auteur, il peut acceder a editer, il peut modifier et supprimer
        //$this->middleware('check.author', ['only'=> ['edit','update','destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rooms= Room::all();
        
        return view('rooms.index', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // affiche la vue de creation d'une room
    public function create()
    {
        // intégre les données pour intégrer les type de room
        $types = Type::all();
        // intégre les données pour intégrer les options(equipement) de room
        $options = Option::all();
                
        return view ('rooms.create', compact('types','options'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    //Creation d'une room dans la bdd 
    public function store(Request $request)
    {
        //validation des champs
        $fields = $request->validate([
            'country'=>'required',
            'city'=>'required',
            'area'=>'required',
            'description'=>'required|max:300',
            'sleeping'=>'required',
            'price'=>'required|max:10',
            'datestart'=>'required',
            'dateend'=>'required',
            'type_id'=>'required',
            'picture1'=> 'required|image|mimes:jpeg,png,jpg,gif|max:2048',
            'picture2'=> 'required|image|mimes:jpeg,png,jpg,gif|max:2048',
            'picture3'=> 'required|image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);
            
        //renomage et redirection pour le stockage des photos        
        $path1 = $request->file('picture1')->store('public/images');
        //on recupère le nom seul de l'image
        $image1 =basename($path1);

        $path2 = $request->file('picture2')->store('public/images');
        $image2 =basename($path2);
        $path3 = $request->file('picture3')->store('public/images');
        $image3 =basename($path3);
        

        //injection du nouveau chemin de path dans le fields
        $fields['picture1']= $image1;
        $fields['picture2']= $image2;
        $fields['picture3']= $image3;

        //ajout de l'user   
        $fields['user_id'] = Auth::user()->id;
        //creation de l'address
        $address = Address::create($fields);
        //ajout de l'address
        $fields['address_id'] = $address->id;       

        // Creation de la room
        $room = Room::create($fields);

        //ajout des options (equipements)
        $room->addOptions( $request['options']);

        //redirection vers la vue
        return redirect(route('rooms.index'));      
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
                
        return view('rooms.show',compact('room'));
        
    }

    public function showAdvertiserRoom(Room $room)
    {
        $rooms = $room->whereUserId(Auth::id())->get();
                
        return view('rooms.advertiser',compact('rooms'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        //
    }
}

resources/views/rooms/advertiser.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "Ajouter un bien " dans l'onglet --}}
@section('title', 'Vos biens')

@section('content')

<div class="d-flex justify-content-around row">
        
    @foreach ($rooms as $room)            
        <div class="card" style="width: 20rem;">
            <img src="{{$room->picture1}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Pays : {{$room->address->country}}</h5>                
                    <h5 class="card-title">Ville : {{$room->address->city}}</h5>               
                <a href="{{route('rooms.show', $room)}}" class="btn btn-primary">Détails</a>
                </div>
        </div> 
    @endforeach      
        
</div>

@endsection

resources/views/rooms/create.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "Ajouter un bien " dans l'onglet --}}
@section('title', 'Ajouter un bien')
 
{{-- creation d'un header --}}
@section('header')

    <h1>Ajouter une Location</h1>
    
@endsection

{{-- creation du contenu --}}
@section('content')

{{-- affichage des erreurs --}}
@include('errors')

{{-- formulaire de creation d'une room --}}
<div class="card" style="width: 50rem;">
    <form action="{{route('rooms.store')}}" method="POST" enctype="multipart/form-data">

        {{-- champs de protection CSRF --}}
        @csrf

        <h3>Creer votre annonce :</h3>

        <div class="form-group">
            <label> Pays </label>
        <input type="text" name="country" class="form-control" placeholder="Saisissez le pays de résidence" value="{{ old('country')}}">
        </div>

        <div class="form-group">
            <label> Ville </label>
        <input type="text" name="city" class="form-control" placeholder="Saisissez la ville de résidence" value="{{old('city')}}">
        </div>

        <div class="form-group">
            <label> Arguments de vente </label>
            <textarea class="form-control" name="description">{{old('description')}}</textarea>
        </div>

        <div class="form-group">
            <label for="exampleFormControlSelect1">Type de logement</label>
                <select class="form-control" name="type_id">
                    @foreach ($types as $type)
                        <option value="{{ $type->id }}">{{ $type->type }}</option>
                    @endforeach                    
                </select>
        </div>

        <div class="form-group">
            <label> Quelle est la superficie du logement en m²</label>            
            <input type="number" class="form-control" step="5" value="30" min="15" max="400" name="area">
        </div>

        <div class="form-group">
            <label> Quelle est le nombre de couchage du logement </label>            
            <input type="number" class="form-control" step="1" value="1" min="1" max="10" name="sleeping">
        </div>
        
        <div class="form-group">
            <label> Tarif à la semaine en euros</label>
            <input type="text" name="price" class="form-control" placeholder="Prix en €">
        </div>

        
        <div class="form-group">
            <label> Début de mise en location</label>
        <input type="date" name="datestart" class="form-control">
        </div>
        
        <div class="form-group">
            <label> Début de fin de mise en location</label>
            <input type="date" name="dateend" class="form-control">
        </div>
        
        <div class="form-group">
            <label> Ajouter des photos</label>            
            <input type="file" name="picture1" class="form-control">
            <input type="file" name="picture2" class="form-control">
            <input type="file" name="picture3" class="form-control">
        </div>
                

        <h4>Equipement</h4>
        
        @foreach ($options as $option)
            <label>
                <span> {{$option->label}} </span>
                <input type="checkbox" value="{{$option->id}}" name="options[]">
            </label><br>     
        @endforeach

        <button type="submit" class="btn btn-primary">proposer le bien</button>
    </form>
    
</div>
    
@endsection

resources/views/rooms/index.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "Ajouter un bien " dans l'onglet --}}
@section('title', 'accueil')

@section('content')

<div class="d-flex justify-content-around row">
        
    @foreach ($rooms as $room)            
        <div class="card" style="width: 20rem;">
            
            <img src=" {{asset("storage/images/{$room->picture1}") }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Pays : {{$room->address->country}}</h5>                
                    <h5 class="card-title">Ville : {{$room->address->city}}</h5>                
                    <p class="card-text">Type de logement : {{$room->type->type}}</p>
                    <p class="card-text">Surface:  {{$room->area}} m²</p>
                    <p class="card-text">Nombre de couchage:  {{$room->sleeping}}</p>
                    <p class="card-text">Descriptif:  {{$room->description}}</p>
                    <p class="card-text">prix à la semaine:  {{$room->price}} €</p>
                <a href="{{route('rooms.show', $room)}}" class="btn btn-primary">Détails</a>
                </div>
        </div> 
    @endforeach      
        
</div>

@endsection

resources/views/rooms/show.blade.php
{{-- etend app.blade.php --}}
@extends('layouts.app')

{{-- ajoute le titre "Ajouter un bien " dans l'onglet --}}
@section('title', 'detailroom')

@section('content')     


        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-4">                    
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                              <div class="carousel-item active">
                                <img src="{{asset("storage/images/{$room->picture1}") }}" class="d-block w-100" alt="...">
                              </div>
                              <div class="carousel-item">
                                <img src="{{asset("storage/images/{$room->picture2}") }}" class="d-block w-100" alt="...">
                              </div>
                              <div class="carousel-item">
                                <img src="{{asset("storage/images/{$room->picture3}") }}" class="d-block w-100" alt="...">
                              </div>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                            </a>
                          </div>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Pays : {{$room->address->country}}</h5>
                        <h5 class="card-title">Ville : {{$room->address->city}}</h5>
                        <p class="card-text">Type de logement : {{$room->type->type}}</p>
                        <p class="card-text">Surface:  {{$room->area}} m²</p>
                        <p class="card-text">Nombre de couchage:  {{$room->sleeping}}</p>
                        <p class="card-text">Descriptif:  {{$room->description}}</p>
                        <p class="card-text">prix à la semaine:  {{$room->price}} €</p>
                        <p class="card-text"><small class="text-muted">
                            Bien en location du {{$room->datestart}} au {{$room->dateend}}</small></p>
                    </div>
                </div>

            </div>
        </div>
        <h3 style='color:#EC5F5F'>Liste des equipements</h3>  
        <ul class=" list-group-horizontal-lg">
            @foreach ($room->options as $option)                        
                <li class="list-group-item">{{$option->label}}</li>
            @endforeach                        
        </ul>
        <a href="{{route('leasings.create', $room)}}" class="btn btn-primary">Louer</a>
        
        

@endsection